Society-In-Shadow/ExpressedRealms

- Readme.md
- Added Cypress Section
- Did some general cleanup
> Added Cypress section, did some cleanup

- expressedrealms.client/cypress/Components/Login/AddUserProfile.cy.ts
- expressedrealms.client/cypress/Components/profile/ChangePassword.cy.ts
- expressedrealms.client/package-lock.json
- expressedrealms.client/src/components/Login/CreateAccount.vue
- expressedrealms.client/src/components/Login/ForgotPassword.vue
- expressedrealms.client/src/components/Login/ResetPassword.vue
- expressedrealms.client/src/components/Login/UserLogin.vue
- expressedrealms.client/src/components/profile/ChangeEmail.vue
- expressedrealms.client/src/components/profile/ChangePassword.vue
- expressedrealms.client/src/router/index.ts
- Updated all fields to use the new wrapper components
> Update all components to use new wrapper components

- ExpressedRealms.Server/EndPoints/PlayerEndpoints/PlayerEndpoints.cs
- expressedrealms.client/cypress/Components/Login/AddUserProfile.cy.ts
- expressedrealms.client/cypress/Components/profile/EditUserProfile.cy.ts
- expressedrealms.client/src/components/Login/AddUserProfile.vue
- expressedrealms.client/src/components/profile/ChangeEmail.vue
- expressedrealms.client/src/components/profile/ChangePassword.vue
- expressedrealms.client/src/components/profile/EditUserProfile.vue
- expressedrealms.client/src/components/profile/UserProfileBase.vue
- One should now be able to edit all user profile properties after they log in
- Updated player API endpoints to exclusively use the HTTP verbs for add, get and update
- Made buttons more consistent on the profile page
> Add ability to edit user profile

- expressedrealms.client/cypress/support/component-index.html
- expressedrealms.client/index.html
Added lang attributes to some base pages to satisfy djlint
> Fix Megalinter Errors on Main Branch

- expressedrealms.client/cypress/Components/charcters/character/EditCharacter.cy.ts
- expressedrealms.client/cypress/README.md
- expressedrealms.client/cypress/support/component.ts
- expressedrealms.client/env.d.ts
- expressedrealms.client/src/components/LoggedInLayout.vue
- expressedrealms.client/src/components/characters/character/EditCharacter.vue
- expressedrealms.client/src/config/axiosConfig.ts
- expressedrealms.client/src/main.ts
- expressedrealms.client/src/services/Toasters.ts
- Implemented Toasters
- Added documentation regarding how to use them for testing
- Implemented Axios Interceptor
- For 401 errors, will automatically redirect them to the login page
- For 400 errors, will show a warning toaster stating that one or more fields are not implemented correctly
- For anything else, an error toaster will show "An error occurred.  Please try again."
- The Toasters will show up in the top middle of the screen
> Implement Toasters

- ExpressedRealms.Server/ExpressedRealms.Server.csproj
- ExpressedRealms.Server/Program.cs
- Serilog should now be implemented
- Serilog will now catch any errors that might happen during the execution
- Whole app was wrapped in a Try Catch statement according to good practices
- It's currently using a Postgres and Console Sinks
- It's my current intent to implement an Elastic Search sink in a separate ticket, as that will require investigating (#70)
> Added Serilog Support and Added Startup Info

- ExpressedRealms.DB/Characters/Character.cs
- ExpressedRealms.DB/Characters/CharacterConfiguration.cs
- ExpressedRealms.DB/Migrations/20240330070244_FixExpressionSections.Designer.cs
- ExpressedRealms.DB/Migrations/20240330070244_FixExpressionSections.cs
- ExpressedRealms.DB/Migrations/20240330071844_AddExpressionIdToCharacter.Designer.cs
- ExpressedRealms.DB/Migrations/20240330071844_AddExpressionIdToCharacter.cs
- ExpressedRealms.DB/Models/Expressions/Expression.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/CharacterEndPoints.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CharacterDTO.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CharacterListDTO.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CharacterOptionExpression.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CharacterOptions.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CreateCharacterDTO.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/DTOs/CreateCharacterDTOValidator.cs
- ExpressedRealms.Server/Program.cs
- expressedrealms.client/cypress/Components/charcters/character/AddCharacter.cy.ts
- expressedrealms.client/cypress/Components/charcters/character/EditCharacter.cy.ts
- expressedrealms.client/src/FormWrappers/DropdownWrapper.vue
- expressedrealms.client/src/FormWrappers/InputMaskWrapper.vue
- expressedrealms.client/src/FormWrappers/InputTextWrapper.vue
- expressedrealms.client/src/FormWrappers/TextAreaWrapper.vue
- expressedrealms.client/src/components/characters/CharacterList.vue
- expressedrealms.client/src/components/characters/character/AddCharacter.vue
- expressedrealms.client/src/components/characters/character/EditCharacter.vue
- expressedrealms.client/src/components/characters/tiles/CharacterTile.vue
- Missed a migration from the last PR, so got it in this one
- Added Expression Id field to character table
- When creating a character, it will now prompt you to choose an expression.  
- When you select one, it will show a short description of what that expression is
- Added Dropdown Wrapper + Added default slots to the rest of the wrappers
- Character list should now display the expression of the character under the character name
- Edit character will only show the expression, will not let the user modify it.
> Implement Expression on Characters

- ExpressedRealms.Server/ExpressedRealms.Server.csproj
- ExpressedRealms.Server/Program.cs
- Eyes will no longer be blinded
> Implemented Modern Dark Theme for Swagger

- docker-compose.yaml
- The logs should no longer clog up the terminal
> Need to hide pgAdmin logs

- expressedrealms.client/cypress/Components/profile/EditUserProfile.cy.ts
- expressedrealms.client/src/components/navbar/MainNavBar.vue
- expressedrealms.client/src/components/profile/EditUserProfile.vue
- expressedrealms.client/src/components/stonePuller/StonePuller.vue
- expressedrealms.client/src/router/index.ts
- One should now be able to pull stones
- Its on the main navigation bar
- It's entirely front-end based
- Added additional text around it that relates on how to pull stones
> Implement Stone Puller

- expressedrealms.client/src/FormWrappers/DropdownWrapper.vue
- expressedrealms.client/src/FormWrappers/InputMaskWrapper.vue
- expressedrealms.client/src/FormWrappers/InputTextWrapper.vue
- expressedrealms.client/src/FormWrappers/TextAreaWrapper.vue
- expressedrealms.client/src/components/characters/character/EditCharacter.vue
- expressedrealms.client/src/components/profile/EditUserProfile.vue
Added Skeleton Loaders to Form Elements and enabled them on both the character edit page and the user profile page.
> Add skeleton loading support to form wrappers

- expressedrealms.client/src/components/expressions/ExpressionBase.vue
- expressedrealms.client/src/components/expressions/ExpressionSection.vue
- expressedrealms.client/src/components/expressions/ExpressionToC.vue
- Added skeleton loading to expressions
- Came up with a much better way to center the page
- Added scroll to top button to aid in navigation
Resolves #89
> Add skeleton to expressions

- ExpressedRealms.DB/Migrations/20240505200503_AddTotalXPCostToStatLevelTable.Designer.cs
- ExpressedRealms.DB/Migrations/20240505200503_AddTotalXPCostToStatLevelTable.cs
- ExpressedRealms.DB/Models/Statistics/StatLevel.cs
- ExpressedRealms.DB/Models/Statistics/StatLevelConfiguration.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/CharacterEndPoints.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/StatDTOs/SingleStatInfo.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/StatDTOs/StatDetails.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/StatEndPoints.cs
- expressedrealms.client/src/components/characters/character/EditCharacter.vue
- expressedrealms.client/src/components/characters/character/StatLevel.vue
- expressedrealms.client/src/components/characters/character/StatTile.vue
- Updated API to pass through XP Stuff
- Updated API to check XP limit on update
- Updating a stat will now show a success message
- Added Total XP column to the DB, it makes it much easier to determine how much XP they have used
Closes #93
> Stats should now enforce XP Limits

- ExpressedRealms.Repositories.Characters/CharacterRepository.cs
- ExpressedRealms.Repositories.Characters/ExternalDependencies/IUserContext.cs
- ExpressedRealms.Repositories.Characters/Readme.md
- ExpressedRealms.Repositories.Shared/CommonFailureTypes/AlreadyDeletedFailure.cs
- ExpressedRealms.Repositories.Shared/CommonFailureTypes/FluentValidationFailure.cs
- ExpressedRealms.Repositories.Shared/CommonFailureTypes/NotFoundFailure.cs
- ExpressedRealms.Repositories.Shared/ExpressedRealms.Repositories.Shared.csproj
- ExpressedRealms.Repositories.Shared/ExternalDependencies/IUserContext.cs
- ExpressedRealms.Repositories.Shared/Readme.md
- ExpressedRealms.Server/DependencyInjections/UserContext.cs
- ExpressedRealms.Server/EndPoints/CharacterEndPoints/ResultOverrides.cs
- ExpressedRealms.Server/Program.cs
- ExpressedRealms.sln
Moved stuff that will be shared among the different repositories into a shared project, along with the readme stuff
> Created Shared Repository

- .github/workflows/DeployFrontEndToAzureContainer.yml
- client/README.md
Chat GPT suggested that I might need this and it's on githubs official documentation
> Adding Packages Permission to Workflow

- .github/workflows/DeployAPI.yml
Created a copy of the deploy front end workflow and tweaked with parameters specific to the API stuff
> Get API Deployment in Place

- .github/workflows/DeployAPI.yml
Forgot to cleanup the on push stuff at the top of the file
> Fix Web API Changes

- client/src/router/index.ts
- docker-compose.yaml
- Local Dev should now be up and running again 
- Created production section in the docker compose file
- Added redirect on root of site
> Fixed login redirect if on root url

- api/ExpressedRealms.DB/Characters/Character.cs
- api/ExpressedRealms.DB/Characters/CharacterConfiguration.cs
- api/ExpressedRealms.DB/Migrations/20240917054709_MakeFactionsOptionalOnCharacter.Designer.cs
- api/ExpressedRealms.DB/Migrations/20240917054709_MakeFactionsOptionalOnCharacter.cs
- api/ExpressedRealms.Repositories.Characters/CharacterRepository.cs
- api/ExpressedRealms.Repositories.Characters/DTOs/AddCharacterDto.cs
- api/ExpressedRealms.Repositories.Characters/DTOs/AddCharacterDtoValidator.cs
- api/ExpressedRealms.Repositories.Characters/DTOs/EditCharacterDto.cs
- api/ExpressedRealms.Repositories.Characters/DTOs/EditCharacterDtoValidator.cs
- api/ExpressedRealms.Repositories.Characters/DTOs/GetEditCharacterDto.cs
- api/ExpressedRealms.Server/EndPoints/CharacterEndPoints/Requests/CreateCharacterRequest.cs
- api/ExpressedRealms.Server/EndPoints/CharacterEndPoints/Requests/EditCharacterRequest.cs
- api/ExpressedRealms.Server/EndPoints/CharacterEndPoints/Responses/CharacterEditResponse.cs
- client/cypress/Components/charcters/character/AddCharacter.cy.ts
- client/src/components/characters/character/AddCharacter.vue
- client/src/components/characters/character/EditCharacter.vue
- Faction Id should no longer be required
- Fixed error message on the Background textbox on edit
> Faction Id shouldn't be Required

- .github/workflows/DeployAPI.yml
- api/ExpressedRealms.Server/Configuration/DatabaseConfiguration.cs
- api/ExpressedRealms.Server/Program.cs
Should now be a bit more efficient, will reuse builder across all connections
DB stuff now separate from Program.cs
> Another Token Fix for Database

- api/ExpressedRealms.DB/Models/Expressions/ExpressionSectionConfiguration.cs
- api/ExpressedRealms.Repositories.Expressions/ExpressionTextSections/ExpressionTextSectionRepository.cs
- api/ExpressedRealms.Repositories.Expressions/ExpressionTextSections/IExpressionTextSectionRepository.cs
- api/ExpressedRealms.Server/EndPoints/ExpressionEndpoints/ExpressionSubSectionsEndpoints.cs
- api/ExpressedRealms.Server/EndPoints/ExpressionEndpoints/Requests/CreateExpressionSubSectionTextRequest.cs
- client/src/components/expressions/CreateExpressionSection.vue
- client/src/components/expressions/EditExpressionSection.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/components/expressions/ExpressionSection.vue
One should now be able to add sections and sub sections
One should also now be able to delete sections
> 172 implement create section

- client/src/components/expressions/AddExpression.vue
- client/src/components/expressions/EditExpression.vue
- client/src/components/expressions/ExpressionBase.vue
- Added link to Primevue icons 
- Removed image on Expression page
> Quick Cleanup stuff

- Readme.md
- docker-compose.yaml
Tweaks to get this up and running on Fedora 41 and additional documentation
> Fedora Tweaks After Reinstall

- Readme.md
- api/ExpressedRealms.Server/Configuration/AzureStorageConfiguration.cs
- api/ExpressedRealms.Server/Program.cs
- docker-compose.yaml
Finally sat down and implemented the azure blob storage locally using Azurite.
By doing so, I can get the Audit.Net stuff working correctly, specifically this fixes not being able to get the environment user name
> Data Protection Keys - Long Term Fix

- api/ExpressedRealms.DB/Configuration/SetupDatabaseAudit.cs
- api/ExpressedRealms.DB/Migrations/20250119075133_AddExpressionAuditTrail.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250119075133_AddExpressionAuditTrail.cs
- api/ExpressedRealms.DB/Models/Expressions/Expression.cs
- api/ExpressedRealms.DB/Models/Expressions/ExpressionAuditTrail.cs
- api/ExpressedRealms.DB/Models/Expressions/ExpressionAuditTrailConfiguration.cs
- api/ExpressedRealms.DB/UserProfile/PlayerDBModels/User.cs
- api/ExpressedRealms.DB/readme.md
Expressions are now being audited, and inserting new records will now ignore the id and deleted fields
Added documentation on how to add audits to other tables as well
> Expressed realms 183 add auditing to overall expressions

- client/cypress/support/component.ts
- client/src/main.ts
Turns out that I needed to directly import the css files, not scss files
> Expressed Realms #190 - Output Spewing a bunch of none blocking errors

- api/ExpressedRealms.Repositories.Characters/DTOs/AddCharacterDtoValidator.cs
- api/ExpressedRealms.Repositories.Characters/ExpressedRealms.Repositories.Characters.csproj
Taking a look, there isn't much to backport, so this is a small cleanup ticket
> Add Character validator will now check for expression publish type

- client/package-lock.json
- client/package.json
- client/src/FormWrappers/EditorWrapper.vue
- client/src/components/expressions/EditExpression.vue
- client/src/components/expressions/EditExpressionSection.vue
- client/src/main.ts
> Expressed realms#189 add table support to expression sections

- .trivyignore
- client/package-lock.json
- client/package.json
> Need quill in order to run things

- .github/workflows/DeployAPI.yml
- .github/workflows/DeployFrontEnd.yml
- api/Dockerfile
Also API and Frontend should now try building the docker files for PRs
> Fixed docke file

- api/ExpressedRealms.Authentication/Policies.cs
- api/ExpressedRealms.Authentication/UserRoles.cs
- api/ExpressedRealms.Repositories.Powers/Powers/DTOs/Options/DetailedEditInformation.cs
- api/ExpressedRealms.Repositories.Powers/Powers/DTOs/Options/PowerOptions.cs
- api/ExpressedRealms.Repositories.Powers/Powers/DTOs/PowerCreate/CreatePowerModelValidator.cs
- api/ExpressedRealms.Repositories.Powers/Powers/IPowerRepository.cs
- api/ExpressedRealms.Repositories.Powers/Powers/PowerRepository.cs
- api/ExpressedRealms.Repositories.Powers/PowersRepositoryInjections.cs
- api/ExpressedRealms.Server/Configuration/UserRoles/PolicyConfiguration.cs
- api/ExpressedRealms.Server/Configuration/UserRoles/RoleConfiguration.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/PowerEndpoints.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Requests/CreatePower/CreatePowerRequest.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Requests/PowerEdit/EditPowerRequest.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Responses/Options/DetailedEditInformation.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Responses/Options/PowerOptionsResponse.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Responses/PowerList/DetailedInformation.cs
- api/ExpressedRealms.Server/EndPoints/PowerEndpoints/Responses/PowerList/PowerInformationResponse.cs
- api/ExpressedRealms.Server/Program.cs
Implemented API endpoints
Fixed DI in power repository
Simplified the power delete interface
Fixed namespace issues
> Expressed realms#234 implement api endpoints

- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathCreate/CreatePowerPathModel.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathCreate/CreatePowerPathModelValidator.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathEdit/EditPowerPathModel.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathEdit/EditPowerPathModelValidator.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathLIst/EditPowerPathInformation.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/DTOs/PowerPathLIst/PowerPathInformation.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/IPowerPathRepository.cs
- api/ExpressedRealms.Repositories.Powers/PowerPaths/PowerPathRepository.cs
- api/ExpressedRealms.Repositories.Powers/Powers/IPowerRepository.cs
- api/ExpressedRealms.Repositories.Powers/Powers/PowerRepository.cs
- api/ExpressedRealms.Repositories.Powers/PowersRepositoryInjections.cs
And fixed the return type for edit powers
Reading some recommendations online, I will not be adding unit tests to the repository
> Implemented Repository for Power Paths

- client/src/components/expressions/powerPaths/ListPowerPaths.vue
- client/src/components/expressions/powerPaths/ShowPowerPath.vue
- client/src/components/expressions/powers/AddPower.vue
- client/src/components/expressions/powers/ListPowers.vue
- client/src/components/expressions/powers/PowerCard.vue
- client/src/stores/userStore.ts
UserInfo keeps track of user permissions.
Added function to allow the checking of permissions, and tied it to a new UserRoles class
> Add Power Policy to Front End

- api/ExpressedRealms.Repositories.Characters/DTOs/AddCharacterDtoValidator.cs
- api/ExpressedRealms.Server/EndPoints/CharacterEndPoints/CharacterEndPoints.cs
- client/src/components/LoggedInLayout.vue
- client/src/components/Login/LoginBasePlate.vue
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/components/expressions/powers/PowerCard.vue
- client/src/components/navbar/AvatarDropdown.vue
- client/src/components/navbar/MainNavBar.vue
- client/src/services/Authentication.ts
There is now a beta message at the top of the site that says "This site is currently in a BETA state, not all features or content is in place."
Said message is sticky and will persist on the screen
The expression/system/treasured tales pages should now look much better on mobile view
The logoff button will now properly redirect the user
> Added Beta Message + Misc Fixes

- api/ExpressedRealms.Characters.API/CharacterEndPoints/CharacterEndPoints.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/CharacterSkillOptionsResponse.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/CharacterSkillsResponse.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/Data/ProficiencyDtos.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/Enums/ModifierType.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/ProficiencyRepository.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/Utilities/ModiferConversions.cs
- api/ExpressedRealms.Characters.Repository/Skills/CharacterSkillRepository.cs
- api/ExpressedRealms.Characters.Repository/Skills/DTOs/SkillDto.cs
- api/ExpressedRealms.Characters.Repository/Skills/DTOs/SkillLevelOptionsDto.cs
- client/src/components/characters/character/skills/SkillDetail.vue
- client/src/components/characters/character/skills/SkillTile.vue
- client/src/components/characters/character/skills/interfaces/CharacterSkillsResponse.ts
- client/src/components/characters/character/skills/interfaces/SkillOptionsResponse.ts
Skills will now show level information
Proficiencies should now correctly calculate based off of level
> Quick fix proficiencies

- api/ExpressedRealms.Knowledges.Repository/Knowledges/IKnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.Repository/Knowledges/KnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.UseCases.Tests.Unit/EditKnowledgeUseCaseTests.cs
- api/ExpressedRealms.Knowledges.UseCases/Knowledges/EditKnowledge/EditKnowledgeModel.cs
- api/ExpressedRealms.Knowledges.UseCases/Knowledges/EditKnowledge/EditKnowledgeModelValidator.cs
- api/ExpressedRealms.Knowledges.UseCases/Knowledges/EditKnowledge/EditKnowledgeUseCase.cs
- api/ExpressedRealms.Knowledges.UseCases/Knowledges/EditKnowledge/IEditKnowledgeUseCase.cs
Got use case plus tests in place
> Edit Knowledge is now in place with unit tests #398

- client/src/components/knowledges/KnowledgeList.vue
- client/src/components/public/AboutUs.vue
- client/src/components/public/stores/publicExpressionStore.ts
Updated expressions with new content, knowledges should now be sorte by name, tweaked about us
> General Content Update for Marketing Pages

- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
- client/src/components/public/AboutUs.vue
- client/src/components/public/PublicMenu.vue
- client/src/router/Objects/RouteMeta.ts
- client/src/router/Routes/PublicRoutes.ts
- client/src/router/index.ts
- client/src/stores/userStore.ts
Contact Us is now behind a feature flag
Updated About Us with new Snippet
> Update marketing stuff part3

- client/src/components/navbar/MainNavBar.vue
- client/src/router/index.ts
Feature Flag Redirection should now work again on navigation
> Fix Redirect Issue for feature flag

- api/ExpressedRealms.Powers.API/PowerPrerequisites/PowerPrerequisiteEndpoints.cs
- api/ExpressedRealms.Powers.Repository/Powers/PowerRepository.cs
- documentation/fedoraSetup.md
Category will now be added correctly on create
Fixed 2nd power on a power path not showing the correct number of prerequisites
> Fix add power issues

- api/ExpressedRealms.Blessings.API/Blessings/GetAllBlessings/Blessing.cs
- api/ExpressedRealms.Blessings.API/Blessings/GetAllBlessings/GetAllBlessingsEndpoint.cs
- api/ExpressedRealms.Blessings.API/Blessings/GetAllBlessings/Level.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/GetBlessingsUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/GetBlessings/BlessingLevelReturnModel.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/GetBlessings/BlessingReturnModel.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/GetBlessings/GetBlessingsUseCase.cs
- api/ExpressedRealms.Expressions.Repository/ExpressionTextSections/ExpressionTextSectionRepository.cs
- api/ExpressedRealms.Expressions.UseCases.Tests.Unit/DeleteTextSectionUseCaseTests.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/DeleteTextSection/DeleteTextSectionUseCase.cs
- client/src/components/blessings/BlessingItem.vue
- client/src/components/blessings/BlessingList.vue
- client/src/components/blessings/stores/blessingsStore.ts
- client/src/components/blessings/types.ts
- client/src/components/expressions/EditExpressionSection.vue
- client/src/components/knowledges/KnowledgeList.vue
- client/src/components/knowledges/stores/knowledgeStore.ts
- client/src/components/public/AboutUs.vue
Advantages / Disadvantages / Mixed Blessings will now show up on the Rule Book tab
Fixed loading issue with Knowledges
Delete Section Use Case will now blocks deleting this section
> Add Blessing UI

- api/ExpressedRealms.DB/Characters/Character.cs
- api/ExpressedRealms.DB/Migrations/20250801005648_AddCharacterKnowledgeMappingTables.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250801005648_AddCharacterKnowledgeMappingTables.cs
- api/ExpressedRealms.DB/Models/Knowledges/CharacterKnowledgeMappings/CharacterKnowledgeMapping.cs
- api/ExpressedRealms.DB/Models/Knowledges/CharacterKnowledgeMappings/CharacterKnowledgeMappingConfiguration.cs
- api/ExpressedRealms.DB/Models/Knowledges/CharacterKnowledgeSpecializations/CharacterKnowledgeSpecialization.cs
- api/ExpressedRealms.DB/Models/Knowledges/CharacterKnowledgeSpecializations/CharacterKnowledgeSpecializationConfiguration.cs
- api/ExpressedRealms.DB/Models/Knowledges/Configuration/KnowledgesDbContextPartial.cs
- api/ExpressedRealms.DB/Models/Knowledges/KnowledgeEducationLevels/KnowledgeEducationLevel.cs
- api/ExpressedRealms.DB/Models/Knowledges/KnowledgeModels/Knowledge.cs
Added Character Knowledge Mapping table
Added Character Knowledge Specialization Table
> Add knowledge mapping tables - #461

- client/src/components/public/UpcomingEvents.vue
2nd attempt at getting the map to open up natively on events page
> Trying different approach for map URL

- api/ExpressedRealms.Knowledges.UseCases.Tests.Unit/CharacterKnowledgeMappingTests/DeleteKnowledgeFromCharacterUseCaseTests.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Delete/DeleteKnowledgeFromCharacterModel.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Delete/DeleteKnowledgeFromCharacterModelValidator.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Delete/DeleteKnowledgeFromCharacterUseCase.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Delete/IDeleteKnowledgeFromCharacterUseCase.cs
> Delete knowledge from character #464

- api/ExpressedRealms.DB/Migrations/20250803003732_AddTotalXPCosts_ToEducationLevels.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250803003732_AddTotalXPCosts_ToEducationLevels.cs
- api/ExpressedRealms.DB/Models/Knowledges/KnowledgeEducationLevels/KnowledgeEducationLevel.cs
- api/ExpressedRealms.DB/Models/Knowledges/KnowledgeEducationLevels/KnowledgeEducationLevelConfiguration.cs
- api/ExpressedRealms.Knowledges.Repository/CharacterKnowledgeMappings/CharacterKnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.Repository/CharacterKnowledgeMappings/ICharacterKnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.UseCases.Tests.Unit/CharacterKnowledgeMappingTests/UpdateKnowledgeForCharacterUseCaseTests.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Edit/UpdateKnowledgeForCharacterModelValidator.cs
- api/ExpressedRealms.Knowledges.UseCases/CharacterKnowledgeMappings/Edit/UpdateKnowledgeForCharacterUseCase.cs
Created new columns to keep track of total spent xp for the given level
XP spent is cumulative over the levels now, not differential
> Fix Xp cost #478

- api/ExpressedRealms.Knowledges.Repository/CharacterKnowledgeMappings/CharacterKnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.Repository/CharacterKnowledgeMappings/ICharacterKnowledgeRepository.cs
- api/ExpressedRealms.Knowledges.Repository/KnowledgeSpecializations/IKnowledgeSpecializationRepository.cs
- api/ExpressedRealms.Knowledges.Repository/KnowledgeSpecializations/KnowledgeSpecializationRepository.cs
- api/ExpressedRealms.Knowledges.UseCases.Tests.Unit/KnowledgeSpecializationTests/CreateSpecializationUseCaseTests.cs
- api/ExpressedRealms.Knowledges.UseCases.Tests.Unit/KnowledgeSpecializationTests/EditSpecializationUseCaseTests.cs
- api/ExpressedRealms.Knowledges.UseCases/KnowledgeSpecializations/CreateSpecialization/CreateSpecializationUseCase.cs
- api/ExpressedRealms.Knowledges.UseCases/KnowledgeSpecializations/EditSpecialization/EditSpecializationModel.cs
- api/ExpressedRealms.Knowledges.UseCases/KnowledgeSpecializations/EditSpecialization/EditSpecializationModelValidator.cs
- api/ExpressedRealms.Knowledges.UseCases/KnowledgeSpecializations/EditSpecialization/EditSpecializationUseCase.cs
- api/ExpressedRealms.Knowledges.UseCases/KnowledgeSpecializations/EditSpecialization/IEditSpecializationUseCase.cs
Added use case + tests
Updated Create with trim on notes field
Closes #468
> Add edit specialization use case #468

- client/src/components/characters/character/knowledges/KnowledgeTile.vue
- client/src/components/public/legal/CodeOfConduct.vue
Cancel button will now show up after an item has been picked
> After Initial Knolwedge Pick, You don't have a way to cancel the edit

- client/src/components/expressions/ExpressionBase.vue
- client/src/components/navbar/navMenuItems/ExpressionMenuItem.vue
Also, clicking expression tiles should be much less flaky now
closes #506
> Navigation will now properly redirect on expressions

- api/ExpressedRealms.Repositories.Admin/DTOs/UserListDto.cs
- api/ExpressedRealms.Repositories.Admin/UsersRepository.cs
- api/ExpressedRealms.Server/EndPoints/AdminEndpoints/AdminEndpoints.cs
- api/ExpressedRealms.Server/EndPoints/AdminEndpoints/Dtos/UserListDto.cs
- client/src/components/players/Objects/Player.ts
- client/src/components/players/PlayerList.vue
- client/src/components/players/Services/PlayerConfirmationPopupService.ts
- client/src/components/players/Stores/PlayerListStore.ts
- client/src/components/players/Tiles/PlayerTile.vue
> Added Bypass and Updated Player List UI

- client/src/components/LoggedInLayout.vue
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/components/navbar/MainNavBar.vue
- client/src/components/stonePuller/StonePuller.vue
- client/src/router/Routes/OverallNavigationRoutes.ts
Generator will now have a new max width that is generally defined
All pages were updated to utilize the new space
Code of Conduct will no longer redirect to marketing pages
Hide faction tab for now
Closes #508, #520, #521
> Various Fixes

- api/ExpressedRealms.Expressions.API/ExpressionEndpoints/GetExpressionId/ExpressionNameResponse.cs
- api/ExpressedRealms.Expressions.API/ExpressionEndpoints/GetExpressionId/GetExpressionIdByNameEndpoint.cs
- api/ExpressedRealms.Expressions.API/ExpressionSubSectionEndpoints/Responses/ExpressionBaseResponse.cs
- api/ExpressedRealms.Knowledges.API/CharacterKnowledges/CharacterKnowledgeEndpoints.cs
- api/ExpressedRealms.Knowledges.API/KnowledgeSpecializations/CharacterKnowledgeSpecializationsEndpoints.cs
- api/ExpressedRealms.Powers.API/PowerEndpoints/PowerEndpoints.cs
- api/ExpressedRealms.Powers.API/PowerPathEndpoints/PowerPathEndpoints.cs
- api/ExpressedRealms.Powers.API/PowerPrerequisites/PowerPrerequisiteEndpoints.cs
- api/ExpressedRealms.Powers.Reporting/powerCards/PowerCardReport.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerCardReport/GetPowerCardReportUseCase.cs
- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
- client/src/components/characters/character/EditCharacter.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/components/navbar/MainNavBar.vue
- client/src/stores/expressionStore.ts
- client/src/stores/userStore.ts
Added feature flag for Inventory
Removed Show Rule Book, Show Treasured Tales, Show Character Knowledges feature flags
Closes #502, #503, #504
> Add and Remove Feature Flags

- api/ExpressedRealms.Authentication/Policies.cs
- api/ExpressedRealms.Authentication/UserRoles.cs
- api/ExpressedRealms.Expressions.API/ExpressionEndpoints/ExpressionEndpoints.cs
- api/ExpressedRealms.Expressions.API/ExpressionEndpoints/GetExpressionBooklet/GetExpressionBookletEndpoint.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressedRealms.Expressions.UseCases.csproj
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionBooklet/GetExpressionBookletModel.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionBooklet/GetExpressionBookletModelValidator.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionBooklet/GetExpressionBookletUseCase.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionBooklet/IGetExpressionBookletUseCase.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionCmsReport/GetExpressionCmsReportUseCase.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionCmsReport/IGetExpressionCmsReportUseCase.cs
- api/ExpressedRealms.Powers.API/PowerPathEndpoints/PowerPathEndpoints.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerBookletReport/GetPowerBookletReportUseCase.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerBookletReport/GetPowerBookletReportUseCaseModelValidator.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerBookletReport/IGetPowerBookletReportUseCase.cs
- api/ExpressedRealms.Server/Configuration/UserRoles/PolicyConfiguration.cs
- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/stores/userStore.ts
Threw reports behind permissions
Removed Feature flag in favor of permissions
Closes #534
Closes #535
> Add Expression Booklet Report

- api/ExpressedRealms.Characters.API/CharacterEndPoints/CharacterEndPoints.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/CharacterSkillsResponse.cs
- api/ExpressedRealms.Characters.Repository/Skills/CharacterSkillRepository.cs
- api/ExpressedRealms.Characters.Repository/Skills/DTOs/SkillDto.cs
- api/ExpressedRealms.DB/Migrations/20250817062641_AddTotalXpToSkillLevelTable.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250817062641_AddTotalXpToSkillLevelTable.cs
- api/ExpressedRealms.DB/Models/Skills/SkillLevel.cs
- api/ExpressedRealms.DB/Models/Skills/SkillLevelConfiguration.cs
- client/src/components/characters/character/skills/EditSkillDetail.vue
- client/src/components/characters/character/skills/SkillDetail.vue
- client/src/components/characters/character/skills/SkillTile.vue
- client/src/components/characters/character/skills/interfaces/CharacterSkillsResponse.ts
Total XP is now being populated from DB
Updated calculations to take that into consideration as opposed to per level updates
Closes #537
> Fix Skill Experience

- api/ExpressedRealms.Expressions.Reports/ExpressedRealms.Expressions.Reports.csproj
- api/ExpressedRealms.Expressions.Reports/ExpressionCMSReport/ExpressionCmsReport.cs
- api/ExpressedRealms.Powers.Reporting/ExpressedRealms.Powers.Reporting.csproj
- api/ExpressedRealms.Powers.Reporting/PowerBookletFormat/PowerBookletReport.cs
- api/ExpressedRealms.Powers.Reporting/powerCards/PowerCardReport.cs
- api/ExpressedRealms.Shared.Reports/ExpressedRealms.Shared.Reports.csproj
- api/ExpressedRealms.Shared.Reports/HtmlTextFormatter.cs
- api/ExpressedRealms.Shared.Reports/SetStandardHtmlFormatting.cs
- api/ExpressedRealms.sln
- client/cypress/Components/Login/Login.cy.ts
- client/src/FormWrappers/EditorWrapper.vue
- client/src/FormWrappers/FormEditorWrapper.vue
- client/src/components/Login/UserLogin.vue
Created ability to add ordered and unordered lists to general sections
Reports will now show them nicely as shown below
Reports will now more consistently format things across reports
Fixed redirect login issue I encountered
Closes #540
> Fix Bullet Points on Reports

- api/ExpressedRealms.Expressions.Reports/ExpressionCMSReport/ExpressionCmsReport.cs
- api/ExpressedRealms.Powers.Reporting/PowerBookletFormat/PowerBookletReport.cs
They need to be a bit wider for hole punches
Closes #543
> Adjusted Page Margins

- api/ExpressedRealms.Powers.Reporting/powerCards/PowerCardReport.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerCardReport/GetPowerCardReportUseCase.cs
- api/ExpressedRealms.Shared.Reports/ExpressedRealms.Shared.Reports.csproj
It will now actually behave like a 2x6 style report, with all 6 sections on a page, plus cutout guides
Closes #545
> Updated 2x6 Tile Report

- api/ExpressedRealms.Powers.Repository/CharacterPower/CharacterPowerRepository.cs
- api/ExpressedRealms.Powers.Repository/CharacterPower/ICharacterPowerRepository.cs
- api/ExpressedRealms.Powers.UseCases.Tests.Unit/CharacterPower/UpdatePowerForCharacterUseCaseTests.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Edit/IUpdatePowerForCharacterUseCase.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Edit/UpdatePowerForCharacterModel.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Edit/UpdatePowerForCharacterModelValidator.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Edit/UpdatePowerForCharacterUseCase.cs
> Update Power for Character Use Case

- api/ExpressedRealms.Powers.UseCases.Tests.Unit/CharacterPower/DeletePowerFromCharacterUseCaseTests.cs
- api/ExpressedRealms.Powers.UseCases.Tests.Unit/CharacterPower/UpdatePowerForCharacterUseCaseTests.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Delete/DeletePowerFromCharacterModel.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Delete/DeletePowerFromCharacterModelValidator.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Delete/DeletePowerFromCharacterUseCase.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Delete/IDeletePowerFromCharacterUseCase.cs
Also fixed the update use case, forgot to check to make sure items were in fact modified
Closes #552
> Delete power from character use case

- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/CharacterPowerEndpoints.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/Create/CreatePowerMappingEndpoint.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/Create/CreatePowerMappingRequest.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/Delete/DeleteCharacterPowerEndpoint.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/Edit/EditCharacterPowerEndpoint.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/Edit/EditCharacterPowerRequest.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/GetAll/CharacterPowerBaseResponse.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/GetAll/GetCharacterPowersEndpoint.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/GetPickable/CharacterPowerBaseResponse.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/GetPickable/GetCharacterPowersEndpoint.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/SharedResponses/DetailedInformationResponse.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/SharedResponses/PowerPathResponse.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/SharedResponses/PowerResponse.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/SharedResponses/PrerequisiteDetailsResponse.cs
- api/ExpressedRealms.Powers.API/Configuration/PowersAPIConfiguration.cs
- api/ExpressedRealms.Powers.Repository/Powers/IPowerRepository.cs
- api/ExpressedRealms.Powers.Repository/Powers/PowerRepository.cs
- api/ExpressedRealms.Powers.UseCases.Tests.Unit/CharacterPower/AddPowerToCharacterUseCaseTests.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Create/AddPowerToCharacterModel.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Create/AddPowerToCharacterModelValidator.cs
- api/ExpressedRealms.Powers.UseCases/CharacterPower/Create/AddPowerToCharacterUseCase.cs
- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
Add in all API Endpoints
Added "Show Powers on Character" Feature Flag
Add Power API will no longer allow power level to be passed through
Powers inherently know what their levels are, no need to pass it through
closes #555
> Added Character Power Api

- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/CharacterPowerEndpoints.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/GetPowerCards/GetCharacterPowerOptionsEndpoint.cs
- api/ExpressedRealms.Powers.Reporting/powerCards/PowerCardData.cs
- api/ExpressedRealms.Powers.Reporting/powerCards/PowerCardReport.cs
- api/ExpressedRealms.Powers.UseCases/GetCharacterPowerCardReport/GetCharacterPowerCardReportModel.cs
- api/ExpressedRealms.Powers.UseCases/GetCharacterPowerCardReport/GetCharacterPowerCardReportModelValidator.cs
- api/ExpressedRealms.Powers.UseCases/GetCharacterPowerCardReport/GetCharacterPowerCardReportUseCase.cs
- api/ExpressedRealms.Powers.UseCases/GetCharacterPowerCardReport/IGetCharacterPowerCardReportUseCase.cs
- client/src/components/characters/character/powers/PowerTile.vue
- client/src/components/characters/character/powers/stores/characterPowerStore.ts
You can now download the power cards on the users tab
Closes #566
> Add Power Card Report to Character Power Tab

- api/ExpressedRealms.Powers.Reporting/PowerBookletFormat/PowerBookletReport.cs
- api/ExpressedRealms.Powers.Reporting/PowerBookletFormat/PowerData.cs
- api/ExpressedRealms.Powers.Repository/Powers/DTOs/PowerList/DetailedInformation.cs
- api/ExpressedRealms.Powers.Repository/Powers/DTOs/PowerList/PowerInformation.cs
- api/ExpressedRealms.Powers.UseCases/GetPowerBookletReport/GetPowerBookletReportUseCase.cs
> Powers should now correctly sort by power level

- api/ExpressedRealms.Blessings.Repository/Blessings/BlessingRepository.cs
- api/ExpressedRealms.Blessings.Repository/Blessings/IBlessingRepository.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/CreateBlessingUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/CreateBlessings/CreateBlessingModel.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/CreateBlessings/CreateBlessingModelValidator.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/CreateBlessings/CreateBlessingUseCase.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/CreateBlessings/ICreateBlessingUseCase.cs
- api/ExpressedRealms.Shared.UseCases/ExpressedRealms.Shared.UseCases.csproj
Added in new use case
Completes  #607
> Add Blessing Use Case

- api/ExpressedRealms.Blessings.Repository/Blessings/BlessingRepository.cs
- api/ExpressedRealms.Blessings.Repository/Blessings/IBlessingRepository.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/EditBlessingUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/EditBlessings/EditBlessingModel.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/EditBlessings/EditBlessingModelValidator.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/EditBlessings/EditBlessingUseCase.cs
- api/ExpressedRealms.Blessings.UseCases/Blessings/EditBlessings/IEditBlessingUseCase.cs
Added Use Case + Unit Tests
Closes #608
> Edit Blessing Use Case 

- api/ExpressedRealms.Characters.API/CharacterEndPoints/CharacterEndPoints.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/BenefitItemResponse.cs
- api/ExpressedRealms.Characters.Repository/Skills/CharacterSkillRepository.cs
- api/ExpressedRealms.Characters.Repository/Skills/DTOs/BenefitDto.cs
- api/ExpressedRealms.DB/Migrations/20250831200549_UpdateModifierTableWithNoDescription.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250831200549_UpdateModifierTableWithNoDescription.cs
- api/ExpressedRealms.DB/Models/Skills/ModifierType.cs
- api/ExpressedRealms.DB/Models/Skills/ModifierTypeConfiguration.cs
- client/src/components/characters/character/skills/SkillDetail.vue
Renamed Modifier Table, Removed Description, and Updated Character Limits
> Update Stat, Skill, and Modifier Names / Descriptions

- .github/workflows/DeployToProd.yml
- api/ExpressedRealms.Server/Program.cs
Could have sworn I removed all of these job level statements
> Docker Deploys Need to Always Run

- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
- client/cypress/Components/charcters/character/AddCharacter.cy.ts
- client/cypress/Components/charcters/character/EditCharacter.cy.ts
- client/src/components/characters/character/AddCharacter.vue
- client/src/components/characters/character/CharacterDetailTile.vue
- client/src/components/characters/character/EditCharacterDetails.vue
- client/src/stores/userStore.ts
- client/vitest/AddCharacter.spec.ts
Too many people were asking about an incomplete feature
> Hide Faction Info Behind Feature Flag

- api/ExpressedRealms.Expressions.Repository/ExpressionTextSections/ExpressionTextSectionRepository.cs
- api/ExpressedRealms.Expressions.Repository/ExpressionTextSections/IExpressionTextSectionRepository.cs
- api/ExpressedRealms.Expressions.UseCases/ExpressionTextSections/GetExpressionCmsReport/GetExpressionCmsReportUseCase.cs
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/ExpressionBase.vue
Also fixed booklet download names
Fixes #622
> Expression Header will now show up in booklets

- documentation/helloworld.txt
> testing to see if i set this up correctly

- documentation/creatingGPGKeys.md
- documentation/helloworld.txt
> testing directly from vs2022

- client/src/components/blessings/BlessingItem.vue
- client/src/components/blessings/BlessingList.vue
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/ExpressionBase.vue
- client/src/components/expressions/powerPaths/ListPowerPaths.vue
- client/src/components/expressions/powerPaths/PowerPathReorder.vue
- client/src/components/expressions/powerPaths/ShowPowerPath.vue
- client/src/components/expressions/powers/ListPowers.vue
- client/src/components/expressions/powers/PowerCard.vue
- client/src/components/expressions/powers/PowerReorder.vue
- client/src/components/knowledges/KnowledgeItem.vue
- client/src/components/knowledges/KnowledgeList.vue
- client/src/stores/expressionStore.ts
- client/src/stores/userStore.ts
On the frontend, the permissions and feature flags will now be cached, and refresh after 5 minutes
> Cache permissions and feature flags

- api/ExpressedRealms.Blessings.Repository/Blessings/BlessingRepository.cs
- api/ExpressedRealms.Blessings.Repository/Blessings/IBlessingRepository.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/CreateBlessingLevelUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/EditBlessingLevelUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases/BlessingLevels/CreateBlessingLevel/CreateBlessingLevelModelValidator.cs
- api/ExpressedRealms.Blessings.UseCases/BlessingLevels/EditBlessingLevel/EditBlessingLevelModelValidator.cs
- api/ExpressedRealms.Server/Program.cs
- client/src/FormWrappers/FormInputNumberWrapper.vue
- client/src/FormWrappers/Interfaces/FormField.ts
- client/src/components/blessings/AddBlessing.vue
- client/src/components/blessings/BlessingItem.vue
- client/src/components/blessings/BlessingLevels/AddBlessingLevel.vue
- client/src/components/blessings/BlessingLevels/EditBlessingLevel.vue
- client/src/components/blessings/services/blessingConfirmationPopupService.ts
- client/src/components/blessings/services/dialogs.ts
- client/src/components/blessings/stores/blessingsStore.ts
- client/src/components/blessings/types.ts
- client/src/components/blessings/validations/blessingLevelForm.ts
- client/src/utilities/formUtilities.ts
You can now create / edit / delete Blessing Levels
UI will now correctly handle Server Side Validation Errors (this will need to be updated as we go)
Fixed edge cases as I encountered them
> Add Blessing Level UI

- client/src/components/characters/character/powers/stores/characterPowerStore.ts
- client/src/components/characters/character/wizard/CharacterWizard.vue
- client/src/components/characters/character/wizard/knowledges/EditCharacterKnowledge.vue
- client/src/components/characters/character/wizard/knowledges/KnowledgeStep.vue
- client/src/components/characters/character/wizard/knowledges/SelectKnowledgeItem.vue
- client/src/components/characters/character/wizard/powers/PowerStep.vue
- client/src/components/characters/character/wizard/powers/supporting/AddCharacterPower.vue
- client/src/components/characters/character/wizard/powers/supporting/EditCharacterPower.vue
- client/src/components/characters/character/wizard/powers/supporting/PickPowerCard.vue
- client/src/components/characters/character/wizard/powers/supporting/PowerCard.vue
- client/src/components/characters/character/wizard/powers/supporting/PowerDetails.vue
Added Powers to Character Wizard
Added ability to switch between sections
Tweaked a bunch of UI
> Character Wizard Powers

- client/src/components/characters/character/skills/Stores/skillStore.ts
- client/src/components/characters/character/wizard/CharacterWizard.vue
- client/src/components/characters/character/wizard/skills/SkillStep.vue
- client/src/components/characters/character/wizard/skills/supporting/EditSkillDetail.vue
- client/src/components/characters/character/wizard/stats/StatStep.vue
- client/src/components/characters/character/wizard/stats/StatTile.vue
Got the Skills section in the Wizard
Tweaked Stats to not do initial load, and removed deprecated code
> Add Character Wizard Skills Section

- api/ExpressedRealms.Characters.API/CharacterEndPoints/CharacterEndPoints.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/DTOs/CharacterOptionExpression.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/CharacterEditResponse.cs
- api/ExpressedRealms.Characters.API/CharacterEndPoints/Responses/HighLevelExpressionInfoResponse.cs
- api/ExpressedRealms.Characters.Repository/CharacterRepository.cs
- api/ExpressedRealms.Characters.Repository/DTOs/GetEditCharacterDto.cs
- client/src/components/characters/character/stores/characterStore.ts
- client/src/components/characters/character/wizard/CharacterWizard.vue
- client/src/components/characters/character/wizard/basicInfo/AddCharacter.vue
- client/src/components/characters/character/wizard/basicInfo/EditCharacterDetails.vue
- client/src/components/characters/character/wizard/basicInfo/supporting/HighLevelExpressionInfo.vue
- client/src/components/characters/character/wizard/basicInfo/types.ts
- client/src/components/characters/tiles/AddCharacterTile.vue
- client/src/router/Routes/OverallNavigationRoutes.ts
With the feature flag, adding a new character will now start in the wizard
When selecting an expression on add, it will show basic expression information + a link for more info
On Edit, it will also show the same expression information
Upon Adding, it will transition to the edit version of the wizard
> Character Wizard Basic Info

- client/src/components/characters/character/CharacterDetailTile.vue
- client/src/components/characters/character/OverallExperience.vue
- client/src/components/characters/character/SmallStatDisplay.vue
- client/src/components/characters/character/StatTile.vue
- client/src/components/characters/character/knowledges/KnowledgeTile.vue
- client/src/components/characters/character/powers/PowerTile.vue
- client/src/components/characters/character/skills/EditSkillDetail.vue
- client/src/components/characters/character/skills/SkillTile.vue
- client/src/components/characters/character/wizard/CharacterWizard.vue
- client/src/components/characters/character/wizard/basicInfo/EditCharacterDetails.vue
- client/src/router/Routes/OverallNavigationRoutes.ts
Old Character Edit functionality is now blocked when Feature Flag is on
Added Overall Experience breakdown to Character Editor
Added feature flag check to create wizard route
Fixed loading problem with character edit
> Character Wizard Block Sheet Edit Functionality

- api/ExpressedRealms.Blessings.Repository/CharacterBlessings/CharacterBlessingRepository.cs
- api/ExpressedRealms.Blessings.Repository/CharacterBlessings/ICharacterBlessingRepository.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/CharacterBlessingMappings/AddKnowledgeToCharacterUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/CharacterBlessingMappings/UpdateBlessingForCharacterUseCaseTests.cs
- api/ExpressedRealms.Blessings.UseCases/CharacterBlessingMappings/Create/AddBlessingToCharacterUseCase.cs
- api/ExpressedRealms.Blessings.UseCases/CharacterBlessingMappings/Edit/UpdateBlessingForCharacterUseCase.cs
- api/ExpressedRealms.Shared/StartingExperience.cs
- client/src/components/characters/character/CharacterDetailTile.vue
- client/src/components/characters/character/stores/experienceBreakdownStore.ts
- client/src/components/characters/character/wizard/blessings/BlessingStep.vue
- client/src/components/characters/character/wizard/blessings/stores/characterBlessingStore.ts
- client/src/components/characters/character/wizard/blessings/supports/AddCharacterBlessing.vue
- client/src/components/characters/character/wizard/blessings/supports/EditCharacterBlessing.vue
Advantage / Disadvantage Calculation will now ignore Deleted Blessings
Levels will now disable themselves if not enough XP
API will now do proper XP Checks
> Fix XP on Advantages / Disadvantages

- api/ExpressedRealms.Blessings.API/CharacterBlessings/GetAll/CharacterBlessing.cs
- api/ExpressedRealms.Blessings.API/CharacterBlessings/GetAll/GetCharacterBlessingsEndpoint.cs
- api/ExpressedRealms.Blessings.Repository/CharacterBlessings/CharacterBlessingRepository.cs
- api/ExpressedRealms.Blessings.Repository/CharacterBlessings/dto/CharacterBlessingDto.cs
- api/ExpressedRealms.Blessings.UseCases.Tests.Unit/CharacterBlessingMappings/GetAssignedBlessings.cs
- api/ExpressedRealms.Blessings.UseCases/CharacterBlessingMappings/Get/CharacterBlessingReturnModel.cs
- api/ExpressedRealms.Blessings.UseCases/CharacterBlessingMappings/Get/GetAssignedBlessingsUseCase.cs
- api/ExpressedRealms.DB/Migrations/20250913080134_MakeBlessingSubCategoryRequired.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250913080134_MakeBlessingSubCategoryRequired.cs
- api/ExpressedRealms.DB/Models/Blessings/BlessingSetup/Blessing.cs
- api/ExpressedRealms.DB/Models/Blessings/BlessingSetup/BlessingConfiguration.cs
- client/src/components/characters/character/EditCharacter.vue
- client/src/components/characters/character/blessings/BlessingAccordion.vue
- client/src/components/characters/character/blessings/BlessingTab.vue
- client/src/components/characters/character/wizard/blessings/types.ts
Updated Get Use Case to return type and subcategory type
Blessing now requires Sub Category DB Side
> Add Advantages to Character Sheet

- api/ExpressedRealms.Blessings.Repository/CharacterBlessings/CharacterBlessingRepository.cs
- client/src/components/characters/character/wizard/blessings/supports/AddCharacterBlessing.vue
Add Blessing UI will now handle Disadvantage Correctly
Forgot to add Character Id to Spent XP Query
> Quick Fixes for Blessings

- client/package-lock.json
- client/package.json
- client/src/components/characters/character/OverallExperience.vue
- client/src/components/characters/character/knowledges/stores/characterKnowledgeStore.ts
- client/src/components/characters/character/powers/stores/characterPowerStore.ts
- client/src/components/characters/character/wizard/CharacterWizard.vue
- client/src/components/characters/character/wizard/WizardContent.vue
- client/src/components/characters/character/wizard/basicInfo/AddCharacter.vue
- client/src/components/characters/character/wizard/basicInfo/EditCharacterDetails.vue
- client/src/components/characters/character/wizard/basicInfo/supporting/HighLevelExpressionInfo.vue
- client/src/components/characters/character/wizard/blessings/BlessingStep.vue
- client/src/components/characters/character/wizard/blessings/stores/characterBlessingStore.ts
- client/src/components/characters/character/wizard/blessings/supports/AddCharacterBlessing.vue
- client/src/components/characters/character/wizard/blessings/supports/EditCharacterBlessing.vue
- client/src/components/characters/character/wizard/blessings/supports/SelectBlessingItem.vue
- client/src/components/characters/character/wizard/knowledges/AddCharacterKnowledge.vue
- client/src/components/characters/character/wizard/knowledges/KnowledgeStep.vue
- client/src/components/characters/character/wizard/knowledges/SelectKnowledgeItem.vue
- client/src/components/characters/character/wizard/powers/PowerStep.vue
- client/src/components/characters/character/wizard/powers/supporting/PickPowerCard.vue
- client/src/components/characters/character/wizard/powers/supporting/PowerCard.vue
- client/src/components/characters/character/wizard/skills/SkillStep.vue
- client/src/components/characters/character/wizard/stats/StatStep.vue
- client/src/components/characters/character/wizard/stats/StatTile.vue
- client/src/components/characters/character/wizard/stats/stores/statStore.ts
- client/src/components/characters/character/wizard/stores/wizardContentStore.ts
- client/src/components/characters/character/wizard/types.ts
- client/src/components/characters/tiles/AddCharacterTile.vue
All sections in the wizard will now use a popup panel on mobile
The section selector will now hide itself after the you select a section
There is a back button on the top of the mobile view to get back to overall section selector
Punted Stats into a store and updated accordingly
Fixed a bunch of component warnings
On character list, the add button now says "Add Character"
Added section titles to some of the sections
> Add Better Character Wizard Mobile Support

- api/ExpressedRealms.Admin.API/AdminCharacterList/AdminCharacterListEndpoints.cs
- api/ExpressedRealms.Admin.API/AdminCharacterList/GetCharacterList/GetCharacterListEndpoint.cs
- client/src/components/admin/characterList/AdminCharacterList.vue
- client/src/components/admin/characterList/CharacterTile.vue
- client/src/components/admin/characterList/UpdateCharacterXp.vue
- client/src/components/admin/characterList/services/dialogs.ts
- client/src/components/admin/characterList/stores/characterListStore.ts
- client/src/components/admin/characterList/types.ts
- client/src/components/admin/characterList/validators/characterXpForm.ts
- client/src/components/characters/character/ReviewCharacter.vue
- client/src/components/navbar/MainNavBar.vue
- client/src/components/navbar/navMenuItems/SimpleMenuItem.vue
- client/src/components/navbar/navMenuItems/types.ts
- client/src/components/players/PlayerList.vue
- client/src/router/Routes/AdminRoutes.ts
Admin nav bar now has two options, users and player characters
Player Characters will show character name, player name, expression, and background
One can update the available XP for a character
Fixed bug with XP not updating correctly
> Add Character List UI + XP Update

- api/ExpressedRealms.Expressions.Repository/ProgressionPaths/IProgressionPathRepository.cs
- api/ExpressedRealms.Expressions.Repository/ProgressionPaths/ProgressionPathRepository.cs
- api/ExpressedRealms.Expressions.UseCases/ProgressionLevels/Edit/EditProgressionLevelModel.cs
- api/ExpressedRealms.Expressions.UseCases/ProgressionLevels/Edit/EditProgressionLevelModelValidator.cs
- api/ExpressedRealms.Expressions.UseCases/ProgressionLevels/Edit/EditProgressionLevelUseCase.cs
- api/ExpressedRealms.Expressions.UseCases/ProgressionLevels/Edit/IEditProgressionLevelUseCase.cs
- api/ExpressedRealms.Expressions.UseCases/ProgressionPaths/Edit/EditProgressionPathUseCase.cs
> Got Edit Progression Level Use Case in place 

- api/ExpressedRealms.DB/Migrations/20250930065143_AddStatModifiers.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250930065143_AddStatModifiers.cs
- api/ExpressedRealms.DB/Migrations/20250930070536_FixStatModifierName.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250930070536_FixStatModifierName.cs
- api/ExpressedRealms.DB/Migrations/20250930073546_AddNeededTogglesForModiifers.Designer.cs
- api/ExpressedRealms.DB/Migrations/20250930073546_AddNeededTogglesForModiifers.cs
- api/ExpressedRealms.DB/Models/Blessings/BlessingLevelSetup/BlessingLevel.cs
- api/ExpressedRealms.DB/Models/Blessings/BlessingLevelSetup/BlessingLevelConfiguration.cs
- api/ExpressedRealms.DB/Models/Expressions/ProgressionPathSetup/ProgressionLevels/ProgressionLevel.cs
- api/ExpressedRealms.DB/Models/Expressions/ProgressionPathSetup/ProgressionLevels/ProgressionLevelConfiguration.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatGroupMappings/StatGroupMapping.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatGroupMappings/StatModifierGroupConfiguration.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatModifierGroups/StatModifierGroup.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatModifierGroups/StatModifierGroupConfiguration.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatModifiers/StatModifier.cs
- api/ExpressedRealms.DB/Models/ModifierSystem/StatModifiers/StatModifierGroupConfiguration.cs
- api/ExpressedRealms.DB/Models/Powers/PowerSetup/Power.cs
- api/ExpressedRealms.DB/Models/Powers/PowerSetup/PowerConfiguration.cs
Got core tables in place
Got this connected to Blessings, Progression Levels, and Powers
> Add Stat Modifier Tables

- api/ExpressedRealms.Characters.Repository/Proficiencies/Enums/ModifierType.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/ProficiencyRepository.cs
- client/src/components/characters/character/CharacterDetailTile.vue
- client/src/components/characters/character/stores/experienceBreakdownStore.ts
- client/src/components/modifiergroups/stores/modifierGroupStore.ts
Can't add / edit modifiers
Fixed proficiencies not updating after edit in wizard 
Calculation will now work accroding to the tin can
Fixed Reserve Will Power Not being calculated
Character Sheet - Will now say In Character Creation
> Fixed few bugs

- client/src/components/characters/character/wizard/CharacterWizard.vue
When you are on a page, it will now lead you to the next section on the page
> Added Dynamic Previous / Next buttons to Wizard

- api/ExpressedRealms.Admin.API/AdminCharacterList/AdminCharacterListEndpoints.cs
- api/ExpressedRealms.Blessings.API/CharacterBlessings/CharacterBlessingsEndpoints.cs
- api/ExpressedRealms.Characters.Repository/Proficiencies/ProficiencyRepository.cs
- api/ExpressedRealms.Powers.API/CharacterPowerEndpoints/CharacterPowerEndpoints.cs
- api/ExpressedRealms.Shared.FeatureFlags/ReleaseFlags.cs
- client/src/components/characters/character/skills/SkillDetail.vue
- client/src/components/characters/character/stats/StatInfo.vue
- client/src/components/characters/character/stats/StatTile.vue
- client/src/components/characters/character/wizard/basicInfo/EditCharacterDetails.vue
- client/src/components/characters/tiles/AddCharacterTile.vue
- client/src/components/expressions/CmsBase.vue
- client/src/components/expressions/EditExpressionSection.vue
- client/src/router/Routes/OverallNavigationRoutes.ts
- client/src/stores/userStore.ts
With the basic full release of the tool, we no longer need many of the feature flags in here
> Removed most of the feature flags
